import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Fragment, useState, useEffect } from "react";
import { BarChart } from "chartist";
import "chartist/dist/index.css";
import { getSuccessFrequencyTable } from "@/stats";

const inter = Inter({ subsets: ["latin"] });

function ChartArea() {
  const [attribute, setAttribute] = useState("7");
  const [discipline, setDiscipline] = useState("2");
  const [focus, setFocus] = useState(false);
  const [numDice, setNumDice] = useState("2");

  return (
    <Fragment>
      <Chart
        attribute={attribute}
        discipline={discipline}
        focus={focus}
        num_dice={numDice}
      ></Chart>
      <label>
        Attribute:{" "}
        <input
          name="attribute"
          type="number"
          min="7"
          max="12"
          value={attribute}
          onChange={(e) => setAttribute(e.target.value)}
        />
      </label>
      <label>
        Discipline:{" "}
        <input
          name="discipline"
          type="number"
          min="1"
          max="5"
          value={discipline}
          onChange={(e) => setDiscipline(e.target.value)}
        />
      </label>
      <label>
        Focus:{" "}
        <input
          name="focus"
          type="checkbox"
          checked={focus}
          onChange={(e) => setFocus(e.target.checked)}
        />
      </label>
      <label>
        Dice:{" "}
        <input
          name="dice"
          type="number"
          min="2"
          max="5"
          value={numDice}
          onChange={(e) => setNumDice(e.target.value)}
        />
      </label>
    </Fragment>
  );
}

function Chart({ attribute, discipline, focus, num_dice = 2 }) {
  useEffect(() => {
    const frequencyTable = getSuccessFrequencyTable(Number(attribute), Number(discipline), Boolean(focus), Number(num_dice));
    new BarChart(
      "#chart",
      {
        labels: Array.from(frequencyTable.keys()),
        series: Array.from(frequencyTable.values()),
      },
      {
        distributeSeries: true,
      }
    );
  }, [attribute, discipline, focus, num_dice]);
  return (
    <Fragment>
      <div id="chart"></div>
    </Fragment>
  );
}

export default function Home() {
  return (
    <>
      <Head>
        <title>STA Probability Distribution</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Star Trek Adventures</h1>
        <h2>Dice Probability Distributions</h2>
        <ChartArea />
      </main>
    </>
  );
}