import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

const pool_stats = (
  attribute,
  discipline,
  applicable_focus = false,
  num_dice = 2
) => {
  const dc = attribute + discipline;

  // The faces of a d20
  const d20 = Array(20)
    .fill(0)
    .map((x, i) => i + 1);

  // Accepts any number of array-like objects and produces their cartesian product
  const cartesian = (...a) =>
    a.reduce((a, b) => a.flatMap((d) => b.map((e) => [d, e].flat())));

  // The set of all possible rolls (combinations of dice) in the pool
  const possible_rolls = cartesian(...Array(num_dice).fill(d20));

  // An array, for each position i, there are a_i ways to get i successes
  const successes_table = Array(2 * num_dice + 1).fill(0);
  Array.prototype.forEach.call(possible_rolls, (dice) => {
    let successes = 0;
    Array.prototype.forEach.call(dice, (die) => {
      if (die <= dc) {
        successes += 1;
      }
      if (die == 1 || (applicable_focus && die <= discipline)) {
        successes += 1;
      }
    });
    successes_table[successes] += 1;
  });

  // An array, for each position i, a_i is the proportion of outcomes giving a successes
  const normalized_table = Array.prototype.map.call(
    successes_table,
    (x) => x / possible_rolls.length
  );
  return normalized_table;
};

export default function Home() {
  console.log(pool_stats(5, 7, false, 2));
  console.log(pool_stats(5,7, true, 2))
  console.log(pool_stats(5, 7, false, 5))
  return (
    <>
      <Head>
        <title>STA Probability Distribution</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Star Trek Adventures</h1>
        <h2>Dice Probability Distributions</h2>
        <div>Let&apos;s roll some dice!</div>
      </main>
    </>
  );
}
