import Head from "next/head";
import { Fragment } from "react";
import DataArea from "@/components/DataArea";
import loadStaticDataFromFile from "@/lib/load-static-data"; 
import {createComplicationsObject, createSuccessesObject} from "@/lib/static-data-objects";

export default function Home({ successesJSONObj, complicationsJSONObj }) {
  const successes = createSuccessesObject(successesJSONObj);
  const complications = createComplicationsObject(complicationsJSONObj);
  return (
    <Fragment>
      <Head>
        <title>STA Probability Distribution</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main>
        <h1>Star Trek Adventures</h1>
        <h2>Dice Probability Distributions</h2>
        <DataArea successes={successes} complications={complications} />
      </main>
    </Fragment>
  );
}

export const getStaticProps = async () => {
  return { props: { ...await loadStaticDataFromFile() } };
};
