import Head from "next/head";
import { Fragment } from "react";
import DataArea from "@/components/DataArea";

import { CssBaseline } from "@mui/material";

import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';


export default function Home() {
  return (
    <Fragment>
      <CssBaseline />
      <Head>
        <title>STA Probability Distribution</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main>
        <h1>Star Trek Adventures</h1>
        <h2>Dice Probability Distributions</h2>
        <DataArea />
      </main>
    </Fragment>
  );
}
